
GET http://127.0.0.1:8000/api/posts HTTP/1.1

###

POST http://127.0.0.1:8000/api/posts HTTP/1.1
Content-Type: application/json

{
	"title": "11",
	"content": "22",
    "source": "33"
}

###
PUT http://127.0.0.1:8000/api/posts/4
Content-Type: application/json
	
{
	"title": "Dimusto 11",
	"content": "This is liper22",
    "source": "Birendera"
}

###

DELETE http://127.0.0.1:8000/api/posts/5
